### ISSUE TITLE
The performance improvement of the model compared to UNI

### ISSUE THREAD

**Issue by Zhcyoung** [DearCaat/RRT-MIL#16]
我在B站偶然看到了您的报告录像，我很好奇模型相较于UNI的提升效果，您能提供一下对比结果吗

**Comment by DearCaat** [comment]
非常感谢您的关注。我目前手里只有Survival（BLCA、LUAD、LUSC）的数据，因为后续我没有继续扩展该工作，一些关于诊断和分型的结果记不大清了。
| Survival | BLCA (UNI) | LUAD (UNI) | LUSC (UNI) |
| ---- | ---- | ---- | ---- | 
| AB-MIL | 59.67 | 65.05 | 58.88| 
|TransMIL| 61.19 | 66.49| 61.05| 
| RRT-MIL+ABMIL  | 61.54 | 66.38| 62.63|

相较于R50特征，该方法在UNI上的提升并没有这么明显。希望对您有所帮助。

**Comment by Zhcyoung** [comment]
好的 谢谢您，也非常感谢您的及时回复
