### ISSUE TITLE
Question about CR-MSA

### ISSUE THREAD

**Issue by dilint** [DearCaat/RRT-MIL#17]
实验非常充分的工作，但是CR-MSA的结构有点复杂，看了伪代码和代码都没法理解，关于CR-MSA为何如此设计作者可以给出解释或者有什么参考文献？

**Comment by DearCaat** [comment]
感谢您对我们工作的关注！
CR-MSA主要是受MoE的启发，其结构也是一个聚合再分配的过程。在不同区域聚合出代表性特征后，进行多个代表性特征之间的相关性学习后，再将学习后的代表性特征分配给各自的区域特征。整个过程跟MoE的思想比较接近，因此代码也比较接近，推荐看一下MoE和SoftMoE (FROM SPARSE TO SOFT MIXTURES OF EXPERTS) 等工作。

**Comment by dilint** [comment]
很好的思路，感谢作者的及时回复，科研顺利！
