### ISSUE TITLE
CR-MSA

### ISSUE THREAD

**Issue by Blikaokao** [DearCaat/RRT-MIL#2]
Hello, I would like to ask if the code about CR-MSA and feature aggregation predictor has not been completed yet?

**Comment by DearCaat** [comment]
I will upload the full code in the next couple of days. 
[The paper](https://arxiv.org/pdf/2402.17228.pdf) gives pseudo-code about CR-MSA, as for feature aggregation it is the normal MIL model, which has been provided.

**Comment by Blikaokao** [comment]
Ok, thank you very much!

**Comment by Blikaokao** [comment]
Great! Thank you very much for uploading the codes.
