### ISSUE TITLE
labels used in survival prediction

### ISSUE THREAD

**Issue by xiaosongshaokao** [DearCaat/RRT-MIL#4]
Hello, I would like to ask how you get the labels used for survival prediction task. It seems that most of works follow the [MCAT](https://github.com/mahmoodlab/MCAT/tree/master), which does not provide the labels of TCGA-LUSC.

**Comment by FT-ZHOU-ZZZ** [comment]
Thanks for your interests to our work.
All survival labels related to TCGA can be found at https://portal.gdc.cancer.gov/.
Some third-party websites also provide formatted files, such as https://www.cbioportal.org/，https://xenabrowser.net/, https://gdac.broadinstitute.org/, and https://www.linkedomics.org/login.php.

**Comment by xiaosongshaokao** [comment]
Thank you very much!
