### ISSUE TITLE
TCGA-BRCA label

### ISSUE THREAD

**Issue by anhtienng** [DearCaat/RRT-MIL#6]
Hello.

Can you upload a list of slide_id in TCGA-BRCA and their labels ?
I am following the [project HIPT](https://github.com/mahmoodlab/HIPT/tree/master/2-Weakly-Supervised-Subtyping/splits/10foldcv_subtype/tcga_brca), but the number of slides is different from yours.

In that project, I get 831 IDC and 210 ILC, whereas in your paper the respective values are 779 and 198.
<img width="271" alt="image" src="https://github.com/DearCaat/RRT-MIL/assets/47650134/3fd15944-35d3-4ada-af0f-8a86143b8205">

**Comment by DearCaat** [comment]
Thanks for attention to our work.

I've uploaded TCGA-BRCA [labels](https://github.com/DearCaat/RRT-MIL/blob/master/data_label/label_brca.csv).
Moreover, We used the 5-fold cross-valid without val set. If u use `2021` random seed, u can get the same data-split.

Good luck.

**Comment by anhtienng** [comment]
Thank you
