### ISSUE TITLE
Confused about ***CR-MSA***

### ISSUE THREAD

**Issue by shenxiaochenn** [DearCaat/RRT-MIL#7]
Good job! However, I`m confused about ***CR-MSA***.
In the rmsa.py file, the $attn\_regions$, which was as the input to $self.attn = InnerAttention()$ layer, the shape was $(sW,nW*B,C)$.
So, this will result in attention scores being calculated for all regions within a batch. This may not be reasonable, as regions between different WSIs should not calculate attention scores.
![CR-MSA](https://github.com/DearCaat/RRT-MIL/assets/90724430/031f8603-73ef-46e2-aa96-7055989dc907)

**Comment by DearCaat** [comment]
Thanks for attention!

This should be a misunderstanding. In the common tasks of computational pathology, including the cancer diagnosis, sub-typing, and prognosis prediction that the paper deals with, the batch size is constant at 1. This is mainly because each sample (an input sample in the prognosis task contains multiple WSIs) has a variable number of instances.

Some of the code and comments retain the batch size dimension for the sake of uniformity, but in fact this dimension does not exist and is constant at 1.

I hope this answer can solve your confusion. Best wish!

**Comment by shenxiaochenn** [comment]
> Thanks for attention!
> 
> This should be a misunderstanding. In the common tasks of computational pathology, including the cancer diagnosis, sub-typing, and prognosis prediction that the paper deals with, the batch size is constant at 1. This is mainly because each sample (an input sample in the prognosis task contains multiple WSIs) has a variable number of instances.
> 
> Some of the code and comments retain the batch size dimension for the sake of uniformity, but in fact this dimension does not exist and is constant at 1.
> 
> I hope this answer can solve your confusion. Best wish!

Thanks for your reply!
However, I still have some confusion.
Firstly, I was confused about $dispatch_weights$ and  $combine_weights$. Can you further help me break down what they do? I may not have found it in the paper.
And, I found some differences between the pseudo-code in the paper and the actual code in this repository. This confuses me. :no_mouth: :no_mouth: :no_mouth:

![code](https://github.com/DearCaat/RRT-MIL/assets/90724430/3706c750-af92-4080-b0d1-7038c2d06baf)
![aaa](https://github.com/DearCaat/RRT-MIL/assets/90724430/db34e9ca-cf86-44d4-8f4d-cf6a298d6e9c)

**Comment by DearCaat** [comment]
- I've changed the variable names in the [code](https://github.com/DearCaat/RRT-MIL/blob/master/modules/rmsa.py#L304) to make them consistent with the pseudo-code, which is more precise. Moreover, the pseudo-code does not contain any dimension-related operations.
- As for `dispatch_weights` and `combine_weights`, the main idea of them comes from MoE. U can refer it to get more information. In my paper, `combine_weights` aims to aggregate all instances in the region to get representative features of the region. And `dispatch_weights` is to assign the modeled representative features of the region to each instance. The two `dispatch_weights` are feature distributions in two dimensions, respectively.
