### ISSUE TITLE
利用PLIP模型提取病理特征的代码可以提供吗

### ISSUE THREAD

**Issue by hljWmh** [DearCaat/RRT-MIL#9]

**Comment by DearCaat** [comment]
基本与[CLAM仓库](https://github.com/mahmoodlab/CLAM?tab=readme-ov-file#wsi-segmentation-and-patching)代码一致，其中关于PLIP模型的修改可以参见issue #5

**Comment by hljWmh** [comment]
抱歉，我目前还是一名研一新生，专业能力不太够，想从您那获取这个提特征源码学习一下。

**Comment by DearCaat** [comment]
核心代码都在issue #5 中有的，其它都是一些现有包的导入，因为是个项目多个文件，所有不好传上来，你有什么问题可以再问我可以的

**Comment by hljWmh** [comment]
好的谢谢你

**Comment by DearCaat** [comment]
1. 在CLAM仓库中的第一步segemantation，有关于背景信息的去除信息，其仓库使用了OSTU算法，还有其他细节可以看看。
2. 我没有特别关注过特征的值，但一般来说任何特征都可能出现负值，PLIP提取的特征直接使用就行，关于这个问题我也没有更多意见，不好意思

**Comment by hljWmh** [comment]
好的，谢谢
